[project]
name = "docker-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.3",
    "gunicorn>=23.0.0",
    "uvicorn>=0.38.0",
]
